# Generated by Django 5.0.7 on 2024-10-10 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Unnamed Stock', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
