# Generated by Django 5.0.7 on 2024-10-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_current_price_stock_daily_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='daily_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
